export default {
    APP_TOGGLE_MODAL: 'APP_TOGGLE_MODAL',
    APP_TYPE_MODAL: 'APP_TYPE_MODAL',
    APP_SET_MODAL: 'APP_SET_MODAL',
    APP_TOGGLE_SPIN: 'APP_TOGGLE_SPIN',
    APP_SET_SPINNING: 'APP_SET_SPINNING',
    APP_SET_SPIN_RESULT: 'APP_SET_SPIN_RESULT',
    APP_SET_RESULT: 'APP_SET_RESULT',
  };
  