export default {
    RGS_SET_LOADING: 'RGS_SET_LOADING',
    RGS_SET_ERROR: 'RGS_SET_ERROR',
    RGS_TOGGLE_PAGE: 'RGS_TOGGLE_PAGE',
    RGS_SET_PAGE: 'RGS_SET_PAGE',
    RGS_SET_FIELDS: 'RGS_SET_FIELDS',
    RGS_SET_BASIC: 'RGS_SET_BASIC',
    RGS_SET_BASIC_SEC: 'RGS_SET_BASIC_SEC',
    RGS_SET_LOC: 'RGS_SET_LOC',
    RGS_SET_PREF: 'RGS_SET_PREF',
    RGS_SET_PREF_SEC: 'RGS_SET_PREF_SEC',
    RGS_SET_PREF_TRI: 'RGS_SET_PREF_TRI',
    RGS_SET_PREF_FOU: 'RGS_SET_PREF_FOU',
    RGS_SET_PREF_FIV: 'RGS_SET_PREF_FIV',
    RGS_HANDLE_SUBMIT: 'RGS_HANDLE_SUBMIT',
    RGS_HANDLE_APPOINTMENT: 'RGS_HANDLE_APPOINTMENT',
  };
  